import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '../components/Navbar';
import Link from 'next/link';
import nav from '@/styles/Navbar.module.css'
import Carousel from 'react-bootstrap/Carousel';
import carousel from '@/styles/Carousel.module.css';


export default function Home() {
  return (


    <>
      <Head>
        <title>CryptoSkyscraper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={`navbar navbar-expand-lg ${nav.bgCustomColor}`}>
        <div className="container-fluid d-flex justify-content-between">
          {/* Agrupando Logo e Título */}
          <div className="d-flex align-items-center">
            <img src="/crypto-skyscaper-logo.png" alt="Logo" style={{ height: '40px' }} />
            <h1 className="mb-0 ms-2">CryptoSkyscraper</h1>
          </div>

          {/* Botão Connect Wallet */}
          <div className="ms-auto">
          </div>
        </div>
      </nav>

      <Carousel>
        {['salaa1', 'salaa2', 'pol1', 'pol2', 'quar1', 'quar2'].map((imageName, index) => (
          <Carousel.Item key={index}>
            <div className={carousel.carouselImageWrapper}>
              <img
                className={carousel.carouselImage}
                src={`/images/${imageName}.jpg`}
                alt={`Slide ${index + 1}`}
              />
            </div>
            <Carousel.Caption className={carousel.carouselCaption}>
              <div className={carousel.carouselText}>
                <h3>Um novo jeito de investir te espera!</h3>
              </div>
            </Carousel.Caption>
          </Carousel.Item>
        ))}
      </Carousel>

      <div className={styles.fullHeightSection}>
      <div className={styles.propagandaContainer}>
        <h2 className='mb-5'>Bem-vindo ao CryptoSkyscraper</h2>
        <Link href="/crypto-skyscraper" legacyBehavior>
      <a className={styles.checkItOutButton}>Clique para conferir as cotas!</a>
    </Link>
        <p className='mt-5'>Explore o mundo dos investimentos imobiliários de uma maneira totalmente nova!</p>

      </div>
      </div>
    </>
  )
}
